brew "fzf"
brew "git"
brew "gpg"
brew "grc"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "zsh"

tap "thoughtbot/formulae"
brew "rcm"

tap "homebrew/cask-cask"
tap "homebrew/cask-versions"

cask "bitwarden"
cask "firefox-developer-edition"
cask "iterm2"
cask "protonvpn"
