"
" Plugin management using vim-plug
"

" Install vim-plug if it is not installed
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"
" Plugins list
"

call plug#begin()
" common defaults
Plug 'tpope/vim-sensible'
" fuzzy finding
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'reedes/vim-wheel'
" themes
Plug 'chriskempson/base16-vim'
" provide some level of support for a large
" variety of languages
Plug 'sheerun/vim-polyglot'
" additional filetype support
Plug 'bfontaine/Brewfile.vim'
call plug#end()

"
" Theme
"

if filereadable(expand("~/.vimrc_background"))
    let base16colorspace=256
    source ~/.vimrc_background
endif

"
" Mouse (get over it)
"

" enable in all modes
set mouse=a

"
" Leader key
"
" The benefit of using spacebar as the leader key is that the
" leader key can be quickly struck by either hand
let mapleader=" " 

"
" Quick access remaps of native commands
"

" reload vimrc
nmap <leader>s :so ~/.vimrc<cr>

" start typing a colon command by pressing ; instead of ⇧;
nmap ; :
" since ; is remapped above, make it available as ;;
nmap ;; ;

" start typing a shell command by pressing 1 instead of press ⇧;1
nmap 1 :!

" toggle between the current buffer and the previous buffer
nmap <leader><leader> :b#<cr>

" write, write+quit, and quit
nmap <leader>w :w<cr>
nmap <leader>x :x<cr>
nmap <leader>q :q<cr>

" toggle line numbers
nmap <leader>n :set number!<cr>

" make only the current visible
nmap <leader>o :only<cr>

" sort visually selected lines
vnoremap <leader>s :sort<cr>

"
" Settings
"

set noswapfile

" show tabs as 4 spaces
set tabstop=4
" > indent with 4 spaces
set shiftwidth=4
" tab indent with 4 spaces
set expandtab

" use the osx clipboard so you can copy/paste to/from other apps
" - in order to copy from vim to system clipboard, use y in normal mode
" - in order to paste from system clipboard to vim, use p in normal mode
set clipboard=unnamed

"
" Plugin Configurations
"

" FZF

" use silver searcher for things like gitignore exclusions
" https://github.com/junegunn/fzf.vim/issues/121#issuecomment-209534405
let $FZF_DEFAULT_COMMAND='ag -g ""'

" quick access to files, buffers, and searching
nmap <leader>e :Files<cr>
nmap <leader>b :Buffers<cr>
nmap <leader>f :Ag<cr>
